language: node_js
node_js:
- '10.8'
deploy:
  provider: cloudfoundry
  username: nasir.m@hotmail.co.uk
  password:
    secure: KRw5fGMIrhE5yHKKpSXcZ4doPIQiuuTPUYw3h0CrgMVZr1GmKvGQsIrgJImpYe9YsCw8BE4XFcEtclRorzlXI+ZLZ1iiLsr9esi15Ej95qTk+fFb6yfv/JL2lShXRyepfXY14CdoxkfROqSrjaHEAbEkwWT9ujFd18u1rEbZGhG/l2/6nHXuMitvB59yXfb4wyHiWsdxIW8GPzkQe6f2vXDrlG7QJ6AVjGgFaDTjMoCTrh1RsgLnWPt7soaKDITvE7Gmzv2RME88B+Mb6CnCdSefNFW1hFjFBvxUC28H97rI3/GjM0R81qASTe9/IND8i4etmPpr37Mn/F088ezn1UEVNQVsWPclxakrB/83uzHtx+1reu8skcGe7PIYkf5bgL+DibegyccNhl/jchs5+XvPBRA1/I90zClXdgTHknzL7FmJn4byTvRNeMe7hX4YymaMjd66vGanGkQRzfoA/zTFnkFh3LmyJA7Kle+pUV9rL7x9mSAEBJJAeuAPzu1ewNLXyv+fw5urL8v+WwkZmzRlKBQBsvW1he5/+nlrudyT0c3UWwtOaElBlF5mChv9EPli2kUS/sv+kzjv8XXotUtHmmcsR8wBpmjyUXyYHY7fr/5GUmJLBQDwEpC6sYuWeetu583RrGYGjWujGLuIUntRrqv9VK+3BilvyvKbtpI=
  api: https://api.cloud.service.gov.uk
  organization: dhsc-skills-for-care-nmds-sc-2
  space: sandbox
